services:
  flask_app:
    image: talrozman/iac-ai
    container_name: flask
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - OLLAMA_URI=Ollama:11434
    networks:
      - app_network
    depends_on:
      # - mongo
      - ollama

  ollama:
    image: ollama/ollama
    container_name: Ollama
    ports:
      - "11434:11434"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
